variant: fcos
version: 1.4.0
storage:
  files:
    # CRI-O DNF module
#    - path: /etc/dnf/modules.d/cri-o.module
#      mode: 0644
#      overwrite: true
#      contents:
#        inline: |
#          [cri-o]
#          name=cri-o
#          stream=1.17
#          profiles=
#          state=enabled
#    # YUM repository for kubeadm, kubelet and kubectl
    - path: /etc/yum.repos.d/fedora.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [fedora]
          name=NEXUS Fedora $releasever - $basearch
          baseurl=http://192.168.1.80:8081/repository/fedora-home/releases/$releasever/Everything/$basearch/os/
          enabled=1
          countme=1
          metadata_expire=7d
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
          skip_if_unavailable=False

    - path: /etc/yum.repos.d/fedora-updates.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [updates]
          name=NEXUS Fedora $releasever - $basearch - Updates
          baseurl=http://192.168.1.80:8081/repository/fedora-home/updates/$releasever/Everything/$basearch/
          enabled=1
          countme=1
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          metadata_expire=6h
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
          skip_if_unavailable=False

    - path: /etc/yum.repos.d/fedora-updates-modular.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [updates-modular]
          name=NEXUS Fedora Modular $releasever - $basearch - Updates
          baseurl=http://192.168.1.80:8081/repository/fedora-home/updates/$releasever/Modular/$basearch/
          enabled=1
          countme=1
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          metadata_expire=6h
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
          skip_if_unavailable=False

    - path: /etc/yum.repos.d/fedora-modular.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [fedora-modular]
          name=NEXUS Fedora Modular $releasever - $basearch
          baseurl=http://192.168.1.80:8081/repository/fedora-home/releases/$releasever/Modular/$basearch/os/
          enabled=1
          countme=1
          metadata_expire=7d
          repo_gpgcheck=0
          type=rpm
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
          skip_if_unavailable=False

    - path: /etc/yum.repos.d/fedora-cisco-openh264.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [fedora-cisco-openh264]
          name=NEXUS Fedora $releasever openh264 (From Cisco) - $basearch
          baseurl=http://192.168.1.80:8081/repository/fedora-codecs-home/openh264/$releasever/$basearch/os/
          type=rpm
          enabled=1
          metadata_expire=14d
          repo_gpgcheck=0
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
          skip_if_unavailable=True

    - path: /etc/yum.repos.d/kubernetes.repo
      mode: 0644
      overwrite: true
      contents:
        inline: |
          [kubernetes]
          name=NEXUS Kubernetes
          baseurl=http://192.168.1.80:8081/repository/kubernetes-home/
          enabled=1
          gpgcheck=1
          repo_gpgcheck=0
          gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg    # configuring automatic loading of br_netfilter on startup

    - path: /etc/modules-load.d/br_netfilter.conf
      mode: 0644
      overwrite: true
      contents:
        inline: br_netfilter
    # setting kernel parameters required by kubelet
    - path: /etc/sysctl.d/kubernetes.conf
      mode: 0644
      overwrite: true
      contents:
        inline: |
          net.bridge.bridge-nf-call-iptables=1
          net.ipv4.ip_forward=1
passwd: # setting login credentials
  users:
    - name: core
      password_hash: "$y$j9T$IhkUF7pj2rOJGzcvj7xad/$LK5p3T298qXuDasicX5pv7an9agjQcBHLMIPXJgxhW0"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+oFX50QkM0MxL3RdK7wYIbfF5tuRcNrOMSqn/dAZrYXGhsd6CGI7iSUcbXsJP9sO8lHswwKBtvStoQLYAVfRLCruHZrvsWErqNHdrxePRLpIs8/u9vmQQ04dhGkvYsHfkIhrh8bBmybe/9A0x1cNWljcpR/zU+h/4aSD+w/NJoFDSl/SwzNUaBvYv3dXzSAMmd9LtM1tgxfgJ7I3KI35yKnGOrlkroW7JWuY9qGFhnGzvMHaqz1Zgon8scFfEH+TUSZxrtI3mg2KWH2R9tCaB0KCt6glIgjbWrVgxmNyTps4MGt1SmchXZlXwrnWYqKC3+4cYcFQknorwVZhE/Byu0ZHJUhl0Snn8xoOHhAtfGIKxs3xWKxC7/yotFRhhYrhuS3ep1AZNqfbFZWQX+quD/5xzKQtyeZJ7EUDefXEufF3ZI6SwYxSyGGdVYzCbF9hh13qkuBCMA91+LomcN0p7/02UosNbUimeEwKP0CvGnsk7i3z8qhhi25kTbL6tzCk= andrey@Victus
systemd:
  units:
    # Installing vim as a layered package with rpm-ostree
    - name: rpm-ostree-install-python.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer python with rpm-ostree
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # `--allow-inactive` ensures that rpm-ostree does not return an error
        # if the package is already installed. This is useful if the package is
        # added to the root image in a future Fedora CoreOS release as it will
        # prevent the service from failing.
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive python python3-libselinux python3-jmespath pip
#        ExecStartPost=/usr/bin/pip install jmespath
        ExecStart=/bin/touch /var/lib/%N.stamp

        [Install]
        WantedBy=multi-user.target
