---
- name: Backup repository
  become: true
  shell: mv /etc/yum.repos.d /etc/yum.repos.d."$(date +%d%m%Y%H%M)"

- name: Create repo directory
  become: true
  ansible.builtin.file:
    path: "/etc/yum.repos.d"
    state: directory

- name: Copy repos
  become: true
  ansible.builtin.template:
    src: "{{ item }}"
    dest:  "/etc/yum.repos.d/{{ (((item | split('/'))[-1])|splitext)[0] }}.repo"
  with_fileglob:
    - templates/*.j2
