#!/usr/bin/env ansible-playbook
---
- hosts:
    - worker03.home.local
    # - frontend01.home.local
    # - worker01.home.local
    # - worker02.home.local
#  gather_facts: no
  roles:
    - role: add_disk
      become: yes
    # - role: ping
    #   vars:
    #    desc: "show all nodes"
